name: Deploy

on:
  push:
    tags:
    - "[1-9][1-9][1-9]-[1-9][1-9]-[1-9][1-9]*"
    - '^\d{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])$*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build .
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION
